"""Curated pipeline-level corpus cases for the 4.1.0 parity surface.

Inputs (configs, routes, drives) are curated by hand; every expected value is
regenerated by running the live reference engine through
``pipeline_harness.run_case`` - never hand-written. Mirrors the reference
family response contract: detection 400 "Suspicious activity detected",
auto-ban 403 "IP has been banned", live ban 403 "IP address banned",
rate-limit 429 + Retry-After, IP-gate 403 "Forbidden".
"""

from __future__ import annotations

from typing import Any

PIPELINE_SUITES: dict[str, list[dict[str, Any]]] = {}

IP = "192.0.2.10"
IP_OTHER = "192.0.2.11"
IP_EXEMPT = "192.0.2.30"
IP_EXEMPT_BLACK = "192.0.2.32"
IP_GEO_CN = "198.51.100.9"
IP_GEO_US = "198.51.100.8"
IP_WHITELISTED = "192.0.2.40"
ATTACK = "<script>alert(1)</script>"

PIPELINE_SUITES["pipeline_ip_control"] = [
    {
        "id": "ip_blacklist_forbidden",
        "config": {"blacklist": [IP_OTHER]},
        "drives": [{"client_ip": IP_OTHER, "url_path": "/api"}],
    },
    {
        "id": "ip_blacklist_passive_mode_allows",
        "config": {"blacklist": [IP_OTHER], "passive_mode": True},
        "drives": [{"client_ip": IP_OTHER, "url_path": "/api"}],
    },
    {
        "id": "ip_whitelist_skips_detection",
        "config": {"whitelist": [IP_WHITELISTED]},
        "drives": [
            {"client_ip": IP_WHITELISTED, "url_path": "/api", "body": ATTACK},
        ],
    },
    {
        "id": "exempt_ip_skips_user_agent_block",
        "config": {
            "exempt_ips": [IP_EXEMPT],
            "blocked_user_agents": ["evilbot/1.0"],
        },
        "drives": [
            {
                "client_ip": IP_EXEMPT,
                "url_path": "/api",
                "headers": {"User-Agent": "evilbot/1.0"},
            },
        ],
    },
    {
        "id": "non_exempt_user_agent_blocked",
        "config": {"blocked_user_agents": ["evilbot/1.0"]},
        "drives": [
            {
                "client_ip": IP,
                "url_path": "/api",
                "headers": {"User-Agent": "evilbot/1.0"},
            },
        ],
    },
    {
        "id": "blacklist_beats_exemption",
        "config": {
            "exempt_ips": [IP_EXEMPT_BLACK],
            "blacklist": [IP_EXEMPT_BLACK],
        },
        "drives": [{"client_ip": IP_EXEMPT_BLACK, "url_path": "/api"}],
    },
    {
        "id": "geo_blocked_country_denied",
        "config": {"blocked_countries": ["CN"]},
        "geo_countries": {IP_GEO_CN: "CN", IP_GEO_US: "US"},
        "drives": [{"client_ip": IP_GEO_CN, "url_path": "/api"}],
    },
    {
        "id": "geo_unresolved_open_in_blocklist_mode",
        "config": {"blocked_countries": ["CN"]},
        "geo_countries": {IP_GEO_CN: "CN"},
        "drives": [{"client_ip": IP_OTHER, "url_path": "/api"}],
    },
    {
        "id": "geo_whitelist_mode_denies_unresolved",
        "config": {"whitelist_countries": ["US"]},
        "geo_countries": {IP_GEO_CN: "CN", IP_GEO_US: "US"},
        "drives": [
            {"client_ip": IP_GEO_CN, "url_path": "/api"},
            {"client_ip": IP_OTHER, "url_path": "/api"},
        ],
    },
    {
        "id": "exempt_ip_still_country_blocked",
        "config": {
            "blocked_countries": ["CN"],
            "exempt_ips": [IP_GEO_CN],
        },
        "geo_countries": {IP_GEO_CN: "CN"},
        "drives": [{"client_ip": IP_GEO_CN, "url_path": "/api"}],
    },
    {
        "id": "route_ip_whitelist_denies_other_ip",
        "config": {},
        "routes": {"/api/private": {"ip_whitelist": [IP_WHITELISTED]}},
        "drives": [
            {"client_ip": IP_WHITELISTED, "url_path": "/api/private"},
            {"client_ip": IP_OTHER, "url_path": "/api/private"},
            {"client_ip": IP_OTHER, "url_path": "/api"},
        ],
    },
    {
        "id": "route_blacklisted_user_agent",
        "config": {},
        "routes": {"/api/admin": {"blocked_user_agents": ["evilbot/1.0"]}},
        "drives": [
            {
                "client_ip": IP,
                "url_path": "/api/admin",
                "headers": {"User-Agent": "evilbot/1.0"},
            },
        ],
    },
]

PIPELINE_SUITES["pipeline_rate_limits"] = [
    {
        "id": "global_limit_429_with_retry_after",
        "config": {"rate_limit": 2, "rate_limit_window": 60},
        "drives": [
            {"client_ip": IP, "url_path": "/api"},
            {"client_ip": IP, "url_path": "/api"},
            {"client_ip": IP, "url_path": "/api"},
            {"client_ip": IP_OTHER, "url_path": "/api"},
        ],
    },
    {
        "id": "endpoint_tier_independent_of_global",
        "config": {
            "rate_limit": 5,
            "rate_limit_window": 60,
            "endpoint_rate_limits": {"/api/heavy": [2, 60]},
        },
        "drives": [
            {"client_ip": IP, "url_path": "/api/heavy"},
            {"client_ip": IP, "url_path": "/api/heavy"},
            {"client_ip": IP, "url_path": "/api/heavy"},
            {"client_ip": IP, "url_path": "/api"},
            {"client_ip": IP, "url_path": "/api"},
            {"client_ip": IP, "url_path": "/api"},
            {"client_ip": IP, "url_path": "/api"},
        ],
    },
    {
        "id": "exempt_ip_never_rate_limited",
        "config": {
            "rate_limit": 2,
            "rate_limit_window": 60,
            "exempt_ips": [IP_EXEMPT],
        },
        "drives": [
            {"client_ip": IP_EXEMPT, "url_path": "/api"},
            {"client_ip": IP_EXEMPT, "url_path": "/api"},
            {"client_ip": IP_EXEMPT, "url_path": "/api"},
        ],
    },
    {
        "id": "rate_limit_passive_mode_allows",
        "config": {
            "rate_limit": 1,
            "rate_limit_window": 60,
            "passive_mode": True,
        },
        "drives": [
            {"client_ip": IP, "url_path": "/api"},
            {"client_ip": IP, "url_path": "/api"},
        ],
    },
    {
        "id": "route_rate_limit_tier",
        "config": {"rate_limit": 100, "rate_limit_window": 60},
        "routes": {"/api/login": {"rate_limit": 1, "rate_limit_window": 30}},
        "drives": [
            {"client_ip": IP, "url_path": "/api/login"},
            {"client_ip": IP, "url_path": "/api/login"},
            {"client_ip": IP, "url_path": "/api"},
        ],
    },
]

PIPELINE_SUITES["pipeline_detection_response"] = [
    {
        "id": "attack_blocked_400_contract_body",
        "config": {},
        "drives": [
            {"client_ip": IP, "url_path": "/api", "body": ATTACK},
        ],
    },
    {
        "id": "attack_custom_error_response_overrides_body",
        "config": {"custom_error_responses": {400: "custom detection body"}},
        "drives": [
            {"client_ip": IP, "url_path": "/api", "body": ATTACK},
        ],
    },
    {
        "id": "attack_passive_mode_logs_only",
        "config": {"passive_mode": True},
        "drives": [
            {"client_ip": IP, "url_path": "/api", "body": ATTACK},
            {"client_ip": IP, "url_path": "/api", "body": ATTACK},
        ],
    },
    {
        "id": "attack_passive_mode_on_block_payload",
        "config": {"passive_mode": True},
        "drives": [
            {"client_ip": IP, "url_path": "/api", "body": ATTACK},
        ],
    },
    {
        "id": "attack_on_block_payload_active",
        "config": {},
        "drives": [
            {"client_ip": IP, "url_path": "/api", "body": ATTACK},
        ],
    },
    {
        "id": "route_detection_exclusion_allows_attack",
        "config": {},
        "routes": {"/api/open": {"enable_suspicious_detection": False}},
        "drives": [
            {"client_ip": IP, "url_path": "/api/open", "body": ATTACK},
            {"client_ip": IP, "url_path": "/api", "body": ATTACK},
        ],
    },
    {
        "id": "route_excluded_detection_header",
        "config": {},
        "routes": {"/api/probe": {"excluded_detection_headers": ["X-Skip-Scan"]}},
        "drives": [
            {
                "client_ip": IP,
                "url_path": "/api/probe",
                "headers": {"X-Skip-Scan": ATTACK},
            },
        ],
    },
    {
        "id": "second_attack_hits_400_without_ban",
        "config": {},
        "drives": [
            {"client_ip": IP, "url_path": "/api", "body": ATTACK},
            {"client_ip": IP, "url_path": "/api", "body": ATTACK},
            {"client_ip": IP, "url_path": "/api", "body": ATTACK},
        ],
    },
]

PIPELINE_SUITES["pipeline_headers_cors"] = [
    {
        "id": "error_response_carries_default_security_headers",
        "config": {},
        "drives": [
            {"client_ip": IP, "url_path": "/api", "body": ATTACK},
        ],
    },
    {
        "id": "disabled_security_headers_on_error_response",
        "config": {"security_headers": {"enabled": False}},
        "drives": [
            {"client_ip": IP, "url_path": "/api", "body": ATTACK},
        ],
    },
    {
        "id": "custom_security_headers_on_error_response",
        "config": {
            "security_headers": {
                "frame_options": "DENY",
                "custom": {"X-Custom-Header": "custom-value"},
                "csp": {"default-src": ["'self'"]},
                "hsts": {"max_age": 63072000},
            }
        },
        "drives": [
            {"client_ip": IP, "url_path": "/api", "body": ATTACK},
        ],
    },
    {
        "id": "cors_allowed_origin_echoed_on_response",
        "config": {
            "enable_cors": True,
            "cors_allow_origins": ["https://app.example.com"],
        },
        "drives": [
            {
                "client_ip": IP,
                "url_path": "/api",
                "stage": "process_response",
                "headers": {"Origin": "https://app.example.com"},
            },
        ],
    },
    {
        "id": "cors_disallowed_origin_gets_no_cors_headers",
        "config": {
            "enable_cors": True,
            "cors_allow_origins": ["https://app.example.com"],
        },
        "drives": [
            {
                "client_ip": IP,
                "url_path": "/api",
                "stage": "process_response",
                "headers": {"Origin": "https://evil.example.com"},
            },
        ],
    },
    {
        "id": "cors_wildcard_with_credentials_blocked",
        "config": {
            "enable_cors": True,
            "cors_allow_origins": ["*"],
            "cors_allow_credentials": True,
        },
        "drives": [
            {
                "client_ip": IP,
                "url_path": "/api",
                "stage": "process_response",
                "headers": {"Origin": "https://app.example.com"},
            },
        ],
    },
    {
        "id": "cors_disabled_no_cors_headers",
        "config": {"enable_cors": False},
        "drives": [
            {
                "client_ip": IP,
                "url_path": "/api",
                "stage": "process_response",
                "headers": {"Origin": "https://app.example.com"},
            },
        ],
    },
]

PIPELINE_SUITES["pipeline_behavior_rules"] = [
    {
        "id": "return_pattern_rule_bans_after_threshold",
        "config": {
            "behavior_scan_response_body": True,
            "global_behavior_rules": [
                {
                    "rule_type": "return_pattern",
                    "threshold": 2,
                    "window": 3600,
                    "pattern": "status:404",
                    "action": "ban",
                    "ban_duration": 900,
                }
            ],
        },
        "drives": [
            {
                "client_ip": IP,
                "url_path": "/api",
                "stage": "process_response",
                "response_status": 404,
            },
            {
                "client_ip": IP,
                "url_path": "/api",
                "stage": "process_response",
                "response_status": 404,
            },
            {
                "client_ip": IP,
                "url_path": "/api",
                "stage": "process_response",
                "response_status": 404,
            },
            {"client_ip": IP, "url_path": "/api"},
            {"client_ip": IP_OTHER, "url_path": "/api"},
        ],
    },
    {
        "id": "return_pattern_rule_below_threshold_no_ban",
        "config": {
            "behavior_scan_response_body": True,
            "global_behavior_rules": [
                {
                    "rule_type": "return_pattern",
                    "threshold": 5,
                    "window": 3600,
                    "pattern": "status:404",
                    "action": "ban",
                    "ban_duration": 900,
                }
            ],
        },
        "drives": [
            {
                "client_ip": IP,
                "url_path": "/api",
                "stage": "process_response",
                "response_status": 404,
            },
            {
                "client_ip": IP,
                "url_path": "/api",
                "stage": "process_response",
                "response_status": 404,
            },
            {"client_ip": IP, "url_path": "/api"},
        ],
    },
    {
        "id": "return_pattern_rule_passive_mode_never_bans",
        "config": {
            "passive_mode": True,
            "behavior_scan_response_body": True,
            "global_behavior_rules": [
                {
                    "rule_type": "return_pattern",
                    "threshold": 1,
                    "window": 3600,
                    "pattern": "status:404",
                    "action": "ban",
                    "ban_duration": 900,
                }
            ],
        },
        "drives": [
            {
                "client_ip": IP,
                "url_path": "/api",
                "stage": "process_response",
                "response_status": 404,
            },
            {
                "client_ip": IP,
                "url_path": "/api",
                "stage": "process_response",
                "response_status": 404,
            },
            {"client_ip": IP, "url_path": "/api"},
        ],
    },
]
